# WINDOW
remember_window_size    no
initial_window_width    968
initial_window_height   620

# BEGIN_KITTY_THEME
# Solarized Light
include themes/solarized-light
# END_KITTY_THEME

# FONT
font_family Menlo
bold_font   auto
italic_font auto
bold_italic_font    auto
font_size   13.0

# CURSOR
cursor_shape    block
cursor_blink_interval   1

# TAB BAR
tab_bar_edge    top
tab_bar_style   powerline
tab_powerline_style round
