[general]
import = [
  "~/.config/alacritty/themes/solarized_light.toml"
]

[window]
decorations = "Full"
dimensions = { columns = 120, lines = 36 }
opacity = 1
blur = true

[font]
size = 13.0

[font.normal]
family = "menlo"
style = "Regular"

[cursor]
style = { shape = "Block", blinking = "On" }

[scrolling]
history = 10000
multiplier = 3